---

global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v1
    static_configs:
    - targets: 
      - alertmanager:9093
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - prometheus:9090
- job_name: pushgateway
  honor_timestamps: true
  static_configs:
  - targets:
    - pushgateway:9091
- job_name: node_exporter
  honor_timestamps: true
  static_configs:
  - targets:
    - node_exporter:9100
remote_write:
  - url: http://<victoriametrics-addr>:8428/api/v1/write