---

global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v1
    static_configs:
    - targets: 
      - alertmanager:9093
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - prometheus:9090
- job_name: federate
  honor_timestamps: true
  honor_labels: true
  metrics_path: /metrics
  params:
    'match[]':
      - '{job="node_exporter"}'
  static_configs:
  - targets:
    - prometheus:9090
